env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
overrides:
  - files:
      - "**/*.jsx"
    rules:
      react/react-in-jsx-scope: off
      react/prop-types: off
      no-unused-vars: warn
